### ISSUE TITLE
Netcoreapp/standard support

### ISSUE THREAD

**Issue by mcintyre321** [Patrickkk/Newtonsoft.Json.Comparer#2]
Are there any plans to add netcore/standard support? I could submit a PR to this effect, but you'd have to update your CI/packaging.

**Comment by Patrickkk** [comment]
yes, i have already started working on this, but the support for fody nullguard isn't finished yet.

**Comment by sosergio** [comment]
is there any news about this?

**Comment by Patrickkk** [comment]
its now possible so i got it working in branch netstandard while also updating everything else. no nuget push jet, but you could build from source if you are in a hurry

**Comment by Patrickkk** [comment]
A new version has been published to Nuget. It should appear within an hour after validation and indexing
